golemfoundation/octant

client/src/components/Earn/EarnBoxPersonalAllocation/EarnBoxPersonalAllocation.tsx, client/src/hooks/helpers/useEpochPatronsAllEpochs.ts, client/src/hooks/helpers/useIndividualRewardAllEpochs.ts, client/src/hooks/helpers/useTotalPatronDonations.ts
Right now hooks are called in `EarnView` because `enabled` flag is overriden instead of being combined.
=> [FIX] Hooks are called because overriden enabled

client/cypress/e2e/projectsArchive.cy.ts
CI run failed [here](https://github.com/golemfoundation/octant/actions/runs/8520944618/job/23338399322). Possibly because it asserted archive before it could fully load. Additional assertions for skeletons should help.
=> [TEST] CY - projectsArchive - additional checks for skeletons

client/src/components/Earn/EarnRewardsCalculator/EarnRewardsCalculator.tsx
=> OCT-1595 Rewards calculator should not send requests when local validation failed

backend/app/__init__.py, backend/startup.py
My hypothesis is that the database scoped-sessions (that are implicitly created for each flask request) aren't closed properly. It results in the need for creating additional database connections to handle these "idle" sessions and then it makes the overflow. The idea is to make sure that we do ```db.session.remove()``` when every request is retrieved in our Flask application (as it comes out from SO threads and documentation, it doesn't happen automatically)
7. [ ] Tech …
=> OCT-1643: Teardown session after request finished

client/src/components/Allocation/AllocationItemRewards/AllocationItemRewards.tsx, client/src/components/Allocation/AllocationTipTiles/AllocationTipTiles.tsx, client/src/components/Settings/SettingsRecalculatingScore/SettingsRecalculatingScore.tsx, client/src/components/Settings/SettingsUniquenessScoreBox/SettingsUniquenessScoreBox.tsx
=> [HOTFIX] FE fetching uq from currentepoch

backend/app/infrastructure/database/uniqueness_quotient.py, backend/app/infrastructure/routes/user.py, backend/app/modules/uq/controller.py, backend/app/modules/uq/service/preliminary.py, backend/tests/modules/uq/test_preliminary_uq.py, epoch-verifier/src/_deprecated/epoch3/data/context.ts, epoch-verifier/src/_deprecated/epoch3/data/fetcher.ts, epoch-verifier/src/_deprecated/epoch3/data/models.ts, epoch-verifier/src/_deprecated/epoch3/runner.ts, epoch-verifier/src/_deprecated/epoch3/verifications.ts, epoch-verifier/src/_deprecated/epoch3/verifications/budgets.ts, epoch-verifier/src/_deprecated/epoch3/verifications/donations.ts, epoch-verifier/src/_deprecated/epoch3/verifications/utils.ts, epoch-verifier/src/_deprecated/epoch3/verifier.ts, epoch-verifier/src/data/models.ts, epoch-verifier/src/verifications.ts, epoch-verifier/src/verifications/donations.ts, epoch-verifier/src/verifications/utils.ts
=> OCT-1768 & OCT-1767:  Change the verifier logic for E4

client/src/api/calls/safeTransactions.ts, client/src/components/Earn/EarnGlmLock/EarnGlmLock.tsx, client/src/components/shared/ModalOnboarding/ModalOnboarding.tsx, client/src/hooks/queries/useIsContract.ts
=> [HOTFIX]: lock/unlock glm multisig fix

backend/README.md, backend/tests/api-e2e/test_api_info.py, backend/tests/api-e2e/test_api_withdrawals.py, backend/tests/conftest.py, ci/Dockerfile.contracts-v1, contracts-v1/package.json, contracts-v1/yarn.lock, localenv/multideployer/server.py, package.json
=> OCT-1596 Implement automated sanity tests for Info API section

backend/tests/api-e2e/test_api_history.py, backend/tests/conftest.py
=> OCT-1597 Implement automated sanity tests for History endpoint

backend/migrations/versions/8b425b454a86_fix_created_at_field.py
=> FIX-OCT-1839: Set created_at field

backend/tests/api-e2e/conftest.py, backend/tests/api-e2e/test_api_delegation.py, backend/tests/conftest.py
=> OCT-1862: Cover /check in delegation with API Tests

client/src/components/Allocation/Allocation.tsx
=> OCT-2002: Allocate drawer / view should show allocation buttons even when user has no rewards or no projects added

ci/Dockerfile.multideployer, localenv/multideployer/Dockerfile
A very minor improvement - will allow localenv work with older versions of docker.
=> localenv: don't rely on fancy 'new' features of docker

client/src/components/Settings/SettingsPatronModeBox/SettingsPatronModeBox.module.scss, client/src/components/Settings/SettingsPatronModeBox/SettingsPatronModeBox.tsx
=> OCT-2058: Settings → Patron mode help tip appears partially offscreen

client/src/components/shared/Layout/Layout.module.scss, client/src/components/shared/Layout/Layout.tsx, client/src/components/shared/Layout/LayoutTopBar/LayoutTopBar.module.scss, client/src/components/shared/Layout/LayoutTopBar/LayoutTopBar.tsx, client/src/components/ui/TinyLabel/TinyLabel.tsx, client/src/components/ui/TinyLabel/types.ts, client/src/styles/utils/_colors.scss
Check after [PR-528](https://github.com/golemfoundation/octant/pull/528)
---
(1) Developer(s) in coordination with QA decide whether …
=> OCT-2048: Improve display of Sepolia testnet mode warning

backend/app/infrastructure/external_api/safe/message_details.py
We are logging `get_message_details()` 404 errors into stderr while they are actually  handled and expected by then logic. Really simple fix here
9. [ ] When …
=> OCT-2178: Removes verbose logging on 404 while it's actually handled in code

backend/app/infrastructure/external_api/gc_passport/score.py, backend/app/modules/user/antisybil/core.py, backend/app/modules/user/antisybil/service/initial.py
=> OCT-2055: Add caching for antisybil

backend/tests/conftest.py, backend/tests/modules/user/antisybil/test_antisybil.py
=> OCT-2095: Improve test

client/src/api/calls/karmaGap.ts, client/src/components/Project/ProjectMilestones/ProjectMilestones.tsx, client/src/hooks/queries/karmaGap/useMilestonesPerGrantPerProgram.ts
=> [HOTFIX] Karma GAP milestones not fetching -- correct address in different field

backend/v2/epochs/schemas.py
By mistake we forgot that to build API objects from our base class. Missing the cammelCase formatting for default snake_case.
🤦
=> Fixing the issue with variable names in schema objects for fast api

client/cypress/e2e/_16allocationAWOpen.cy.ts, client/cypress/e2e/_18antisybil.cy.ts, client/src/components/Home/HomeGridUQScore/HomeGridUQScore.tsx, client/src/components/Home/HomeGridUQScore/HomeGridUQScoreAddresses/HomeGridUQScoreAddresses.tsx, client/src/components/shared/Layout/LayoutTopBar/LayoutTopBar.tsx, client/src/components/shared/ModalTimeoutListPresence/ModalTimeoutListPresence.tsx, client/src/components/ui/TinyLabel/TinyLabel.tsx
Check after [PR-592](https://github.com/golemfoundation/octant/pull/592)
---
(1) Developer(s) in coordination with QA decide whether …
=> OCT-2230: Antisybil E2E

client/src/api/calls/karmaGap.ts, client/src/hooks/queries/karmaGap/useMilestonesPerGrantPerProgram.ts
- Karma GAP recently refactored its API response schema. This PR makes the neceessary changes.
- Changed the property name from `externalAddresses` to `external` in the `GrantPerProgram` type definition.
- Updated the query logic in `useMilestonesPerGrantPerProgram` to accommodate the new property structure, ensuring compatibility with the updated type.
2. [X] Acceptance criteria are met.
6. [ ] Automated tests are added …
=> [KARMA GAP] API change - externalAddresses to external in GrantPerProgram type

client/src/components/shared/Layout/LayoutTopBar/LayoutTopBar.module.scss, client/src/components/shared/Layout/LayoutTopBar/LayoutTopBar.tsx, client/src/components/ui/Drawer/Drawer.module.scss, client/src/components/ui/Drawer/Drawer.tsx, client/src/components/ui/Drawer/types.ts, client/src/locales/en/translation.json
=> OCT-2259: Improve visibility of exit button in allocation edit mode

backend/v2/allocations/services.py, backend/v2/allocations/socket.py, backend/v2/allocations/validators.py, backend/v2/core/dependencies.py, backend/v2/project_rewards/services.py, backend/v2/projects/services.py
=> OCT-2296: Improve BE stability

backend/app/modules/score_delegation/core.py, backend/tests/modules/score_delegation/test_score_delegation_core.py, client/src/components/Home/HomeGridUQScore/ModalCalculatingUQScore/CalculatingUQScore/CalculatingUQScore.tsx
Lowers the minimal uq score required to make a delegation
---
(1) Developer(s) in coordination with QA decide whether it's required. …
=> HOTFIX: Aligning minimal delegation score to 15

client/src/hooks/queries/donors/utils.ts, client/src/hooks/queries/useSearchedProjects.ts, client/src/hooks/queries/useSearchedProjectsDetails.ts
=> [HOTFIX]: Donors with 0 value & project search projects in current open AW w/o values for total donation & ensure uniq project search results

client/src/components/Home/HomeGridCurrentGlmLock/HomeGridCurrentGlmLock.tsx, client/src/components/Home/HomeGridCurrentGlmLock/RaffleWinnerBadge/RaffleWinnerBadge.module.scss, client/src/components/Home/HomeGridCurrentGlmLock/RaffleWinnerBadge/RaffleWinnerBadge.tsx
=> OCT-2275 GLM Winnings component exists and 'feels' clickable even if user has no winnings

client/src/components/Home/HomeGridCurrentGlmLock/HomeGridCurrentGlmLock.tsx, client/src/components/Home/HomeGridCurrentGlmLock/RaffleWinnerBadge/RaffleWinnerBadge.tsx
=> [FIX]: Sablier stream -- cancelled

backend/v2/allocations/socket.py, backend/v2/project_rewards/router.py, backend/v2/project_rewards/schemas.py, backend/v2/projects/dependencies.py, backend/v2/projects/services/projects_allocation_threshold_getter.py
Fixing `rewards/threshold/{epoch_number}` outside of AW
Removed check if AW is open, adjusted the project multiplier per epoch as it was misaligned aswell.
=> OCT-2363: Fixing rewards/threshold outside of AW

backend/v2/sablier/subgraphs.py
Increase default sablier timeout limit to 4 seconds
---
(1) Developer(s) in coordination with QA decide whether it's required. For …
=> Increase default sablier subgraph timeout limit

client/src/constants/karmaGap.ts
`id` is required for FE to identify epoch 8 in Karma GAP API response.
=> [FEAT]: Karma GAP Epoch 8 id
