- backend/app/legacy/crypto/eip1271.py
- backend/app/legacy/crypto/eip712.py
- backend/app/legacy/crypto/eth_sign/signature.py
- backend/app/modules/common/signature.py
- backend/app/modules/multisig_signatures/service/offchain.py
- backend/app/modules/user/allocations/service/pending.py
- backend/app/modules/user/tos/core.py
- backend/tests/legacy/test_rewards.py
- backend/tests/modules/user/allocations/test_pending_allocations.py
- backend/tests/modules/user/tos/test_tos_core.py
This enables allocations with multisig. As for patron mode toggle - I haven't addressed that.
> OCT-1468 enable allocations with multisig

- client/src/components/Metrics/MetricsEpoch/MetricsEpochGridFundsUsage/MetricsEpochGridFundsUsage.tsx
- client/src/utils/getFormattedEthValue.ts
> [TEST] MetricsEpochGridFundsUsage: increase precision for testnet

- client/src/hooks/queries/donors/useProjectsDonors.ts
> [HOTFIX] Client -- wrong parameter for react-query donors

- client/src/components/Projects/ProjectsTimelineWidget/ProjectsTimelineWidget.tsx
6. [x] The code is merged.
---
> [HOTFIX]: timeline widget - active item

- client/cypress/e2e/rewardsCalculator.cy.ts
- client/cypress/utils/e2e.ts
- client/src/components/Earn/EarnRewardsCalculator/EarnRewardsCalculator.tsx
1. [x] Acceptance criteria are met.
5. [x] Automated tests are added when required.
---
> OCT-1562: Calculator incorrectly converts from gwei

- client/src/components/Allocation/AllocationRewardsBox/AllocationRewardsBox.tsx
> OCT-1538 Wrong percentage value after changes made in Allocation modals

- client/src/components/Metrics/MetricsEpoch/MetricsEpochGridFundsUsage/MetricsEpochGridFundsUsage.tsx
> [HOTFIX]: claimedByUsers fix

- backend/app/modules/octant_rewards/service/pending.py
- backend/tests/modules/octant_rewards/test_pending_octant_rewards.py
> [HOTFIX] Estimated MR and patron rewards for pending epoch

- client/src/components/Earn/EarnHistory/EarnHistoryItemDetails/EarnHistoryItemDateAndTime/utils.ts
- client/src/hooks/subgraph/useEpochTimestampHappenedIn.ts
> [HOTFIX]: handle timestamp in seconds

- client/src/components/Metrics/MetricsEpoch/MetricsEpochGridFundsUsage/MetricsEpochGridFundsUsage.tsx
> [HOTFIX] Metrics pie chart -- ppf / 2 to total, unusedRewards as leftover when AW open

- client/src/components/Earn/EarnHistory/EarnHistoryItemDetails/EarnHistoryItemDetailsRest/EarnHistoryItemDetailsRest.tsx
> [FIX] History element, patron mode donation -- use ETH

- client/src/components/Metrics/MetricsEpoch/MetricsEpochGridFundsUsage/MetricsEpochGridFundsUsage.tsx
> [HOTFIX]: temporary ppf

- backend/app/modules/multisig_signatures/core.py
> FIX-OCT-1572: Ignore errors when 404

- client/src/api/calls/history.ts
- client/src/components/Earn/EarnHistory/EarnHistoryItemDetails/EarnHistoryItemDetailsAllocation/EarnHistoryItemDetailsAllocation.tsx
- client/src/locales/en/translation.json
> OCT-953 History: add leverage: client -- handle leverage unknown

- coin-prices-server/src/index.ts
:warning:. Generate and change CoinGecko API keys.
DONE.
---
--- …
> OCT-1547 CoinGecko: increase plan and expose API to token page

- ci/argocd/templates/octant-application.yaml
> OCT-1579: Add VITE_SAFE_ENDPOINT for testnet

- client/src/services/apiService.ts
> OCT-1594 Axios to not throw CanceledError in the console (false-positives)

- backend/app/constants.py
- backend/app/infrastructure/external_api/bitquery/blocks_reward.py
- backend/app/infrastructure/external_api/bitquery/req_producer.py
1. [x] Acceptance criteria are met.
4. [x] Unit tests are added unless there is a reason to omit them.
5. [x] Automated tests are added when required.
6. [x] The code is merged.
7. [x] Tech documentation is added / updated, reviewed and approved (including mandatory approval by a code owner, should such exist for changed files).
---
> OCT-1474: update bitquery to V2

- client/src/components/Earn/EarnHistory/EarnHistoryItemDetails/EarnHistoryItemDetailsAllocation/EarnHistoryItemDetailsAllocation.tsx
- client/src/components/shared/ProjectAllocationDetailRow/ProjectAllocationDetailRow.tsx
- client/src/components/shared/ProjectAllocationDetailRow/types.ts
- client/src/hooks/queries/useProjectsEpoch.ts
- client/src/hooks/queries/useProjectsIpfs.ts
> [HOTFIX] Correct epoch passed to fetch assets in history

- .github/workflows/ci-run.yml
- .github/workflows/tpl-deploy-app.yml
- .github/workflows/tpl-images.yml
- backend/app/infrastructure/routes/allocations.py
- backend/tests/legacy/test_api_snapshot.py
- ci/Dockerfile.multideployer
- ci/argocd/application.sh
- ci/argocd/get_multideployer_url.sh
- ci/argocd/templates/octant-application.yaml
- localenv/multideployer/Dockerfile
- localenv/multideployer/server.py
These changes were already merged into develop. They need to be merged into master separately.
> OCT-1318 backend api tests (master branch)

- backend/app/infrastructure/routes/snapshots.py
> OCT-1586: wrong data type returned from simulated snapshot

- client/src/hooks/subgraph/useLockedSummarySnapshots.ts
- client/src/hooks/subgraph/useLockedsData.ts
> [HOTFIX] Subgraph pagination

- client/cypress/e2e/allocationItemWindowClosed.cy.ts
- client/cypress/e2e/allocationItemWindowOpen.cy.ts
- client/cypress/e2e/project.cy.ts
- client/cypress/e2e/projects.cy.ts
- client/cypress/e2e/projectsArchive.cy.ts
- client/cypress/utils/e2e.ts
- client/src/components/Projects/ProjectsList/ProjectsList.tsx
- client/src/views/ProjectsView/ProjectsView.module.scss
- client/src/views/ProjectsView/ProjectsView.tsx
> OCT-1610 CY: Projects view assume loaded before they are

- client/src/hooks/helpers/useEpochPatronsAllEpochs.ts
- client/src/hooks/helpers/useIndividualRewardAllEpochs.ts
- client/src/hooks/helpers/useUserAllocationsAllEpochs.ts
> OCT-1606 Metrics to stop calling for allocations, individualRewards and patrons for epoch 0

- backend/README.md
- backend/tests/conftest.py
- backend/tests/legacy/test_api_snapshot.py
- localenv/backend-apitest/entrypoint.sh
- localenv/scripts/images.sh
- package.json
This allows to use usual pytest way of specifying which test should be executed
> api tests: pass args to pytest

- client/cypress/e2e/projects.cy.ts
> [TEST]: CY disable faulty projects test case

- client/src/constants/milestones.ts
> OCT-1591 Epoch timeline: events for E4: client

- client/src/api/calls/projectDonors.ts
- client/src/api/calls/rewards.ts
> OCT-1491 Unify the naming convention for projects_rewards: client

- backend/app/modules/multisig_signatures/service/offchain.py
- backend/tests/modules/multisig_signatures/test_offchain_multisig_signatures.py
> OCT-1512: Uncomment the verifying logic

- backend/app/modules/user/allocations/core.py
- backend/tests/modules/user/allocations/test_core.py
1. [x] Acceptance criteria are met.
3. [x] PR is manually tested by QA when their assistance is required (1).
4. [x] Unit tests are added unless there is a reason to omit them.
5. [x] Automated tests are added when required.
7. [x] Tech documentation is added / updated, reviewed and approved (including mandatory approval by a code owner, should such exist for changed files).
---
> OCT-1605: block allocating as project

- client/cypress/e2e/layout.cy.ts
- client/src/components/shared/Layout/LayoutWallet/LayoutWallet.module.scss
- client/src/components/shared/Layout/LayoutWallet/LayoutWallet.tsx
- client/src/components/ui/Button/Button.module.scss
> OCT-1571: Add link to wallet address view on Etherscan

- client/cypress/e2e/settings.cy.ts
- client/src/components/Settings/SettingsMainInfoBox/SettingsMainInfoBox.tsx
- staking-batch-deposit/yarn.lock
> OCT-1563 CY -- Settings links (fork)

- client/cypress/e2e/settings.cy.ts
>  OCT-1563 CY -- Settings links (fork)

- backend/tests/api-e2e/test_api_projects.py
- backend/tests/conftest.py
- backend/tests/legacy/test_api_projects.py
> OCT-1608 projects api sanity test

- backend/tests/api-e2e/test_api_allocations.py
- backend/tests/api-e2e/test_api_deposits.py
- backend/tests/api-e2e/test_api_snapshot.py
- backend/tests/conftest.py
> OCT 1599 deposits api sanity test

- client/cypress/e2e/settings.cy.ts
- client/src/components/Settings/SettingsLinkBoxes/SettingsLinkBoxes.tsx
- client/src/components/Settings/SettingsLinksInfoBox/SettingsLinksInfoBox.tsx
- client/src/components/Settings/SettingsMainInfoBox/SettingsMainInfoBox.tsx
> OCT-1563 CY -- Settings links

- backend/migrations/versions/58536423cfdd_unify_all_individual_rewards_to_vanilla_.py
> fix: fix migrations

- client/cypress/e2e/settings.cy.ts
- client/src/components/Earn/EarnBoxGlmLock/EarnBoxGlmLock.tsx
- client/src/components/Earn/EarnBoxPersonalAllocation/EarnBoxPersonalAllocation.tsx
- client/src/components/Settings/SettingsLinkBoxes/SettingsLinkBoxes.tsx
- client/src/components/Settings/SettingsLinksInfoBox/SettingsLinksInfoBox.tsx
- client/src/components/Settings/SettingsMainInfoBox/SettingsMainInfoBox.tsx
- client/src/hooks/helpers/useManageTransactionsPending.ts
> OCT-1043: When locking GLM, the Available now value should not display a skeleton loader

- backend/tests/api-e2e/test_api_snapshot.py
- backend/tests/conftest.py
> OCT-1602 Snapshot API sanity tests

- backend/app/exceptions.py
- backend/app/modules/score_delegation/core.py
- backend/app/modules/score_delegation/service/simple_obfuscation.py
> fix: pass address to GP api, not hashes

- backend/app/modules/user/tos/core.py
- backend/tests/api-e2e/test_api_patron_mode.py
- backend/tests/conftest.py
- backend/tests/helpers/signature.py
> OCT-1618 Patron mode sanity test 

- backend/migrations/versions/1f5a0f69733a_unify_proposals_to_projects.py
- backend/migrations/versions/58536423cfdd_unify_all_individual_rewards_to_vanilla_.py
> OCT-1576 & OCT-1492: Fix altering migrations

- backend/app/context/manager.py
- backend/app/infrastructure/database/allocations.py
- backend/app/settings.py
- backend/startup.py
- client/src/components/shared/Layout/LayoutConnectWallet/LayoutConnectWallet.tsx
> [SYNC] master => develop (resolve conflicts)

- client/src/components/Metrics/MetricsEpoch/MetricsEpoch.tsx
> OCT-1662: Implement QF & remove threshold: client - metrics view

- client/cypress/e2e/earn.cy.ts
- client/src/components/Earn/EarnHistory/EarnHistoryItemDetails/EarnHistoryItemDetailsRest/EarnHistoryItemDetailsRest.tsx
- client/src/components/Earn/EarnHistory/EarnHistoryItemDetailsModal/EarnHistoryItemDetailsModal.tsx
> OCT-1673: E2E: App wide fiat support - earn view

- client/cypress/e2e/allocationItemWindowOpen.cy.ts
- client/cypress/e2e/allocationRewardsBox.cy.ts
- client/cypress/e2e/allocationSummary.cy.ts
- client/cypress/e2e/settings.cy.ts
- client/src/components/Allocation/AllocationNavigation/AllocationNavigation.tsx
- client/src/components/Allocation/AllocationSummary/AllocationSummary.tsx
- client/src/components/Allocation/AllocationSummaryProject/AllocationSummaryProject.tsx
> OCT-1675: E2E: App wide fiat support - allocation view

- client/cypress/e2e/projects.cy.ts
- client/src/components/shared/Rewards/Rewards.tsx
> OCT-1672: E2E: App wide fiat support - projects view

- client/cypress/e2e/project.cy.ts
> OCT-1671: E2E: App wide fiat support - project view

- client/cypress/e2e/metrics.cy.ts
- client/src/components/Metrics/MetricsEpoch/MetricsEpochGridBelowThreshold/MetricsEpochGridBelowThreshold.tsx
- client/src/components/Metrics/MetricsEpoch/MetricsEpochGridFundsUsage/MetricsEpochGridFundsUsage.tsx
- client/src/components/Metrics/MetricsEpoch/MetricsEpochGridRewardsUnusedAndUnallocatedValue/MetricsEpochGridRewardsUnusedAndUnallocatedValue.tsx
- client/src/components/Metrics/MetricsEpoch/MetricsEpochGridTopProjects/MetricsEpochGridTopProjects.tsx
- client/src/components/Metrics/MetricsEpoch/MetricsEpochGridTotalDonationsAndPersonal/MetricsEpochGridTotalDonationsAndPersonal.tsx
- client/src/components/Metrics/MetricsGeneral/MetricsGeneralGridTotalEthStaked/MetricsGeneralGridTotalEthStaked.tsx
- client/src/components/Metrics/MetricsGeneral/MetricsGeneralGridTotalGlmLockedAndTotalSupply/MetricsGridTotalGlmLockedAndTotalSupply.tsx
- client/src/components/Metrics/MetricsGrid/MetricsGridTileValue/MetricsGridTileValue.tsx
- client/src/components/Metrics/MetricsGrid/MetricsGridTileValue/types.ts
- client/src/components/Metrics/MetricsPersonal/MetricsPersonalGridTotalRewardsWithdrawals/MetricsPersonalGridTotalRewardsWithdrawals.tsx
- client/src/components/Metrics/MetricsProjectsList/MetricsProjectsList.tsx
- client/src/components/Metrics/MetricsProjectsList/types.ts
- client/src/components/Metrics/MetricsProjectsListItem/MetricsProjectsListItem.tsx
- client/src/components/Metrics/MetricsProjectsListItem/types.ts
- client/src/hooks/helpers/useCypressHelpers.ts
> OCT-1674: E2E: App wide fiat support - metrics view

- ci/argocd/templates/octant-application.yaml
> OCT-1701: Bump Octant Anvil to 0.0.11 (prevrando fix)

- client/src/components/shared/ModalOnboarding/ModalOnboarding.tsx
> [FIX] ToS not visible after resetting ToS in BE or environment flush

- client/cypress/e2e/metrics.cy.ts
- client/cypress/utils/e2e.ts
- client/src/components/shared/ModalOnboarding/ModalOnboarding.tsx
- client/synpress.config.ts
> [FIX] Onboarding CY

- backend/app/infrastructure/database/user_antisybil.py
- backend/app/modules/user/antisybil/service/initial.py
- backend/tests/conftest.py
- backend/tests/modules/user/antisybil/test_antisybil.py
> Fix incorrect expiration date filtering

- backend/app/modules/octant_rewards/general/service/pending.py
> FIX-OCT-1682: Cover remaining calculate_leftover

- backend/tests/modules/user/allocations/pending/test_allocations_epoch4.py
> OCT-1698: Cover Additional UT case for allocation

- backend/app/extensions.py
- backend/app/infrastructure/__init__.py
- backend/app/settings.py
- backend/tests/conftest.py
- backend/tests/infrastracture/graph/test_gql_retry_backoff.py
1. [x] Acceptance criteria are met.
4. [x] Unit tests are added unless there is a reason to omit them.
5. [x] Automated tests are added when required.
---
> OCT-1712 Add retry if graph complains about reorg

- client/src/constants/milestones.ts
> OCT-1692 Octant App timeline Snapshot date update

- client/src/api/errorMessages/index.ts
- client/src/api/errorMessages/types.ts
- client/src/hooks/helpers/useIndividualRewardAllEpochs.ts
> OCT-1717 Donations vs personal can show negative value

- client/src/components/Settings/SettingsCalculatingUQScore/SettingsCalculatingUQScore.tsx
- client/src/components/Settings/SettingsRecalculatingScore/SettingsRecalculatingScore.tsx
- client/src/components/Settings/SettingsUniquenessScoreBox/SettingsUniquenessScoreBox.tsx
- client/src/hooks/mutations/useRefreshAntisybilStatus.ts
- client/src/hooks/queries/useAntisybilStatusScore.ts
- client/src/store/settings/store.ts
> oct-1735: delegation recalculation

- backend/app/engine/projects/rewards/allocations/__init__.py
- backend/app/engine/projects/rewards/capped_quadratic_funding.py
- backend/app/engine/projects/rewards/funding_cap/percent.py
- backend/app/engine/projects/rewards/preliminary.py
- backend/app/engine/projects/rewards/quadratic_funding.py
- backend/tests/engine/projects/allocations/test_quadratic_funding_allocations.py
- backend/tests/engine/projects/conftest.py
- backend/tests/engine/projects/funding_cap/test_percent_funding_cap.py
- backend/tests/engine/projects/rewards/test_capped_quadratic_funding_rewards.py
- backend/tests/modules/projects/rewards/estimated/test_rewards_epoch4.py
- backend/tests/modules/snapshots/finalized/test_finalizing_snapshots.py
- backend/tests/modules/user/allocations/pending/test_allocations_epoch4.py
> FIX-OCT-1652: Apply QF with UQ. Fixed without surplus.

- client/src/api/calls/checkDelegation.ts
- client/src/components/Settings/SettingsCalculatingUQScore/SettingsCalculatingUQScore.tsx
- client/src/components/Settings/SettingsRecalculatingScore/SettingsRecalculatingScore.tsx
- client/src/components/Settings/SettingsUniquenessScoreAddresses/SettingsUniquenessScoreAddresses.module.scss
- client/src/components/Settings/SettingsUniquenessScoreAddresses/SettingsUniquenessScoreAddresses.tsx
- client/src/components/Settings/SettingsUniquenessScoreAddresses/types.ts
- client/src/components/Settings/SettingsUniquenessScoreBox/SettingsUniquenessScoreBox.tsx
- client/src/hooks/mutations/useCheckDelegation.ts
- client/src/hooks/mutations/useRefreshAntisybilStatus.ts
- client/src/store/settings/store.ts
> OCT-1737: Fetch delegation addresses from BE

- client/src/api/clients/client-react-query.ts
- client/src/hooks/mutations/useCheckDelegation.ts
> OCT-1745 When delegation does not exist, toast error is thrown

- client/src/api/clients/client-react-query.ts
- client/src/api/errorMessages/index.ts
- client/src/hooks/mutations/useCheckDelegation.ts
- client/src/locales/en/translation.json
> OCT-1743 Cancelling new delegation through wallet connect crashes the app

- client/src/components/Settings/ModalSettingsCalculatingYourUniqueness/ModalSettingsCalculatingYourUniqueness.tsx
- client/src/components/Settings/SettingsCalculatingUQScore/SettingsCalculatingUQScore.tsx
- client/src/components/Settings/SettingsRecalculatingScore/SettingsRecalculatingScore.tsx
- client/src/components/Settings/SettingsUniquenessScoreBox/SettingsUniquenessScoreBox.tsx
- client/src/components/shared/ModalOnboarding/ModalOnboarding.tsx
- client/src/constants/delegation.ts
- client/src/hooks/helpers/useModalStepperNavigation.ts
> OCT-1741: PoU FE refactoring

- client/src/api/calls/antisybilStatus.ts
- client/src/components/Settings/SettingsCalculatingUQScore/SettingsCalculatingUQScore.tsx
- client/src/components/Settings/SettingsRecalculatingScore/SettingsRecalculatingScore.tsx
- client/src/components/Settings/SettingsUniquenessScoreBox/SettingsUniquenessScoreBox.tsx
- client/src/hooks/queries/useAntisybilStatusScore.ts
> OCT-1753 Block antisybil requests before ToS is signed

- client/cypress/e2e/rewardsCalculator.cy.ts
- client/src/api/calls/checkDelegation.ts
- client/src/api/clients/client-react-query.ts
- client/src/components/Earn/EarnRewardsCalculator/EarnRewardsCalculator.tsx
- client/src/components/Earn/EarnRewardsCalculator/EarnRewardsCalculatorEstimates/EarnRewardsCalculatorEstimates.tsx
- client/src/components/Earn/EarnRewardsCalculator/EarnRewardsCalculatorEstimates/types.ts
- client/src/components/Earn/EarnRewardsCalculator/EarnRewardsCalculatorUqSelector/EarnRewardsCalculatorUqSelector.module.scss
- client/src/components/Earn/EarnRewardsCalculator/EarnRewardsCalculatorUqSelector/EarnRewardsCalculatorUqSelector.tsx
- client/src/components/Earn/EarnRewardsCalculator/EarnRewardsCalculatorUqSelector/index.tsx
- client/src/components/Earn/EarnRewardsCalculator/EarnRewardsCalculatorUqSelector/types.ts
- client/src/components/Earn/EarnRewardsCalculator/types.ts
- client/src/components/Earn/EarnRewardsCalculator/utils.ts
- client/src/hooks/helpers/useGetValuesToDisplay.ts
- client/src/hooks/mutations/useCheckDelegation.ts
- client/src/locales/en/translation.json
> OCT-1657 Implement proof of uniqueness: rewards calculator

- client/src/components/Metrics/MetricsProjectsList/MetricsProjectsList.tsx
> [FIX] Metrics project - value ignores gwei, wei

- client/src/components/Settings/SettingsUniquenessScoreBox/SettingsUniquenessScoreBox.tsx
> OCT-1754: Update UQ score in BE on initial load of settings view

- client/cypress/utils/e2e.ts
- client/src/components/Allocation/AllocationItemRewards/AllocationItemRewards.tsx
- client/src/components/Allocation/AllocationTipTiles/AllocationTipTiles.tsx
- client/src/components/Settings/SettingsAddressScore/SettingsAddressScore.module.scss
- client/src/components/Settings/SettingsCalculatingUQScore/SettingsCalculatingUQScore.tsx
- client/src/components/Settings/SettingsRecalculatingScore/SettingsRecalculatingScore.tsx
- client/src/components/Settings/SettingsUniquenessScoreBox/SettingsUniquenessScoreBox.tsx
- client/src/hooks/queries/useUqScore.ts
> oct-1756: fetch UQ score every time

- client/src/components/Settings/SettingsUniquenessScoreAddresses/SettingsUniquenessScoreAddresses.module.scss
- client/src/components/Settings/SettingsUniquenessScoreAddresses/SettingsUniquenessScoreAddresses.tsx
- client/src/components/Settings/SettingsUniquenessScoreAddresses/types.ts
- client/src/components/Settings/SettingsUniquenessScoreBox/SettingsUniquenessScoreBox.tsx
> OCT-1760: UQ score loader - remove block loader please

- client/src/api/clients/client-react-query.ts
- client/src/api/errorMessages/index.ts
- client/src/api/errorMessages/types.ts
- client/src/components/Settings/SettingsRecalculatingScore/SettingsRecalculatingScore.tsx
> OCT-1765: Handling of uq score if the user has no budget

- backend/tests/conftest.py
- backend/tests/infrastracture/graph/test_gql_retry_backoff.py
Mocks time for retry on request errors mechanism
Changed a logic of existing test a bit, as we are actually interested in number of retries rather than we tried for X seconds. 
---
(1) Developer(s) in coordination with QA decide whether it's required. For small tickets introducing small changes QA …
> [OCT-1733] Improve test_with_failure in test_gql_retry_backoff

- client/src/components/Settings/SettingsUniquenessScoreAddresses/SettingsUniquenessScoreAddresses.module.scss
- client/src/components/Settings/SettingsUniquenessScoreBox/SettingsUniquenessScoreBox.tsx
> [FIX] wagmi in Safari throws ProviderNotFoundError

- client/src/components/Settings/SettingsUniquenessScoreBox/SettingsUniquenessScoreBox.tsx
> OCT-1774: Historical delegations are not handled properly in new epochs

- backend/app/exceptions.py
- backend/app/infrastructure/database/score_delegation.py
- backend/app/modules/common/crypto/signature.py
- backend/app/modules/modules_factory/current.py
- backend/app/modules/modules_factory/protocols.py
- backend/app/modules/score_delegation/core.py
- backend/app/modules/score_delegation/service/simple_obfuscation.py
- backend/tests/conftest.py
- backend/tests/modules/score_delegation/test_score_delegation_core.py
- backend/tests/modules/score_delegation/test_simple_obfuscation.py
> OCT-1772: Throw an error when secondary is locking

- client/src/components/Settings/ModalSettingsCalculatingYourUniqueness/ModalSettingsCalculatingYourUniqueness.tsx
- client/src/constants/urls.ts
> OCT-1776 Add link to custom GitcoinPassport dashboard in the UI

- client/src/components/Allocation/AllocationTipTiles/AllocationTipTiles.tsx
> OCT-1779 Allocation tip tiles - refresh antisybil status before showing tip tiles

- client/src/api/calls/antisybilStatus.ts
- client/src/hooks/mutations/useRefreshAntisybilStatus.ts
> OCT-1783 Do not show global error toast for PUT /antisybil-status

- client/src/hooks/queries/donors/useProjectDonors.ts
> [FIX] Wrong epoch parameters for donors fetching

- client/src/components/shared/ModalOnboarding/ModalOnboarding.tsx
> [HOTFIX]: delegation secondary TOS

- client/src/components/Earn/EarnGlmLock/EarnGlmLock.tsx
- client/src/components/shared/ModalOnboarding/ModalOnboarding.tsx
- client/src/hooks/helpers/useAppConnectManager.ts
- client/src/hooks/helpers/useAvailableFundsEth.ts
- client/src/hooks/helpers/useAvailableFundsGlm.ts
- client/src/hooks/helpers/useManageTransactionsPending.ts
- client/src/hooks/helpers/useMaxApproveCallback.ts
- client/src/hooks/mutations/useCypressMoveToDecisionWindowClosed.ts
- client/src/hooks/mutations/useCypressMoveToDecisionWindowOpen.ts
- client/src/hooks/queries/useCurrentEpoch.ts
- client/src/hooks/queries/useCurrentEpochEnd.ts
- client/src/hooks/queries/useCurrentEpochProps.ts
- client/src/hooks/queries/useDepositValue.ts
- client/src/hooks/queries/useIsDecisionWindowOpen.ts
- client/src/services/toastService.ts
> [HOTFIX]: wrong chain app crash

- client/src/hooks/helpers/useIndividualRewardAllEpochs.ts
> OCT-1791: Infinite "Loading reward budget" when user has no budget

- client/src/components/Settings/SettingsCalculatingUQScore/SettingsCalculatingUQScore.tsx
- client/src/components/Settings/SettingsUniquenessScoreBox/SettingsUniquenessScoreBox.tsx
- client/src/locales/en/translation.json
- client/src/services/toastService.ts
> OCT-1773 Throw an error whenever delegation is being made from an account with positive GLM lock: client

- client/src/hooks/helpers/useAppConnectManager.ts
- client/src/services/toastService.ts
> [HOTFIX] Wrong network - show / hide toast to change it

- backend/app/infrastructure/database/uniqueness_quotient.py
- backend/app/infrastructure/routes/user.py
- backend/app/modules/uq/controller.py
- backend/app/modules/uq/service/preliminary.py
- backend/tests/modules/uq/test_preliminary_uq.py
Adds user/uq/<int:epoch>/all for listing uq-user pairs
--- …
> OCT-1770: Adds user/uq/<int:epoch>/all for listing uq-user pairs

- client/src/components/Metrics/MetricsProjectsListItem/MetricsProjectsListItem.module.scss
> OCT-1798 Metrics list of projects: add ellipsis for long names

- client/src/components/Metrics/MetricsPersonal/MetricsPersonal.tsx
- client/src/components/Metrics/MetricsPersonal/MetricsPersonalGridPatronDonations/MetricsPersonalGridPatronDonations.tsx
- client/src/components/Metrics/MetricsPersonal/MetricsPersonalGridPatronDonations/types.ts
> OCT-1785: Infinite calls for user budget on metics view

- backend/app/modules/uq/controller.py
- backend/app/modules/uq/core.py
- backend/app/modules/uq/service/preliminary.py
- backend/tests/modules/uq/test_preliminary_uq.py
FIX - Moves the listing of uqs to core from service
---
(2) [Octant Areas & Test Cases](https://docs.google.com/spreadsheets/d/1cRe6dxuKJV3a4Zsk …
> OCT-1770: FIX - Moves the listing of uqs to core from service

- client/src/components/Allocation/AllocationLowUqScore/AllocationLowUqScore.module.scss
- client/src/components/Allocation/AllocationLowUqScore/AllocationLowUqScore.tsx
- client/src/components/Allocation/AllocationLowUqScore/index.tsx
- client/src/components/Allocation/AllocationLowUqScore/types.ts
- client/src/components/Allocation/ModalAllocationLowUqScore/ModalAllocationLowUqScore.module.scss
- client/src/components/Allocation/ModalAllocationLowUqScore/ModalAllocationLowUqScore.tsx
- client/src/components/Allocation/ModalAllocationLowUqScore/index.tsx
- client/src/components/Allocation/ModalAllocationLowUqScore/types.ts
- client/src/components/ui/InputCheckbox/InputCheckbox.module.scss
- client/src/components/ui/InputCheckbox/InputCheckbox.tsx
- client/src/components/ui/InputCheckbox/types.ts
- client/src/locales/en/translation.json
- client/src/views/AllocationView/AllocationView.tsx
> OCT-1807: Implement UQ score warning modal that prevents users from allocating

- client/src/components/Settings/ModalSettingsCalculatingYourUniqueness/ModalSettingsCalculatingYourUniqueness.module.scss
- client/src/components/Settings/ModalSettingsCalculatingYourUniqueness/ModalSettingsCalculatingYourUniqueness.tsx
- client/src/locales/en/translation.json
> [HOTFIX]: calculating your uniqueness modal style

- backend/app/modules/common/synchronized.py
- backend/app/modules/facades/confirm_multisig.py
- backend/app/modules/multisig_signatures/service/offchain.py
> OCT-1516: Improve processing in an asynchronous way

- client/src/components/Settings/SettingsCurrencyBox/SettingsCurrencyBox.tsx
- client/src/components/Settings/SettingsMainInfoBox/SettingsMainInfoBox.module.scss
- client/src/components/Settings/SettingsPatronModeBox/SettingsPatronModeBox.tsx
- client/src/components/Settings/SettingsShowOnboardingBox/SettingsShowOnboardingBox.tsx
- client/src/components/Settings/SettingsShowTipsBox/SettingsShowTipsBox.tsx
- client/src/components/Settings/SettingsUniquenessScoreAddresses/SettingsUniquenessScoreAddresses.module.scss
- client/src/components/Settings/SettingsUniquenessScoreBox/SettingsUniquenessScoreBox.module.scss
- client/src/components/Settings/SettingsUniquenessScoreBox/SettingsUniquenessScoreBox.tsx
- client/src/locales/en/translation.json
> OCT-1806 Improve link placement on UQ tile

- client/src/components/shared/ModalOnboarding/ModalOnboarding.tsx
- client/src/hooks/events/useAllocate.ts
- client/src/views/AllocationView/AllocationView.tsx
> [HOTFIX]: multisig TOS + Allocation

- client/src/constants/milestones.ts
Data from Mattias:
```
Applications open
1 Aug 2024 → 15 Aug 2024
Project updates close
15 Aug 2024
Snapshot vote
19 Aug 2024 → 25 Aug 2024
Allocation Window
13 Oct 2024 → 27 Oct 2024
Epoch Six starts
27 Oct 2024
For the Snapshot vote it'll start at 6pm CEST and end time the same.
For the applications open and close, it'll start at 0:00 and end at 23:59 CEST. And the link, it'll be this: https://octant.fillout.com/t/ok9Rz9pJBxus
```
7. [ ] Tech documentation is added / updated, …
> OCT-1796 Epoch timeline: events for E5: client

- client/src/api/calls/epochAllocations.ts
- client/src/components/Metrics/MetricsEpoch/MetricsEpochGridBelowThreshold/MetricsEpochGridBelowThreshold.tsx
- client/src/components/Metrics/MetricsEpoch/MetricsEpochGridCurrentDonors/MetricsEpochGridCurrentDonors.tsx
- client/src/hooks/queries/donors/useProjectsDonors.ts
- client/src/hooks/queries/useEpochAllocations.ts
- client/src/hooks/queries/useProjectsIpfsWithRewards.ts
> OCT-1725: Combine dozens of frontend requests into just a few

- ci/argocd/templates/octant-application.yaml
> Use local IPFS gateway for test envs

- client/src/components/Allocation/AllocationTipTiles/AllocationTipTiles.module.scss
- client/src/components/Allocation/AllocationTipTiles/AllocationTipTiles.tsx
- client/src/components/Earn/EarnTipTiles/EarnTipTiles.module.scss
- client/src/components/Earn/EarnTipTiles/EarnTipTiles.tsx
- client/src/components/Metrics/MetricsPersonal/MetricsPersonal.module.scss
- client/src/components/Metrics/MetricsPersonal/MetricsPersonal.tsx
- client/src/components/shared/TipTile/TipTile.module.scss
- client/src/components/shared/TipTile/TipTile.tsx
- client/src/components/shared/TipTile/types.ts
- client/src/locales/en/translation.json
- client/src/styles/utils/_mixins.scss
- client/src/svg/misc.ts
- client/src/views/ProjectsView/ProjectsView.module.scss
- client/src/views/ProjectsView/ProjectsView.tsx
> OCT-1659 Update tip tile style

- backend/app/infrastructure/apscheduler.py
- backend/startup.py
Since our app is structured in a way that exceptions are expected, then caught and displayed as valid http responses, sentry must not report those exceptions as issues. It should thus not report "handled" exceptions.
---
(1) Developer(s) in coordination with QA decide whether it's required. For small …
> OCT-1842: Reduce sentry events flood

- backend/tests/api-e2e/conftest.py
- backend/tests/api-e2e/test_api_delegation.py
- backend/tests/conftest.py
> OCT-1860: Cover /delegate with API Tests

- backend/tests/api-e2e/test_api_uq.py
- backend/tests/conftest.py
> OCT-1863: Cover UQ with API Tests

- backend/tests/conftest.py
- ci/argocd/templates/octant-application.yaml
- client/cypress/e2e/_3onboardingTOSNotAccepted.cy.ts
- client/cypress/e2e/_4onboardingTOSAccepted.cy.ts
- client/cypress/e2e/allocationItemWindowClosed.cy.ts
- client/cypress/e2e/allocationItemWindowOpen.cy.ts
- client/cypress/e2e/allocationRewardsBox.cy.ts
- client/cypress/e2e/allocationSummary.cy.ts
- client/cypress/e2e/earn.cy.ts
- client/cypress/e2e/layout.cy.ts
- client/cypress/e2e/metrics.cy.ts
- client/cypress/e2e/patronMode.cy.ts
- client/cypress/e2e/project.cy.ts
- client/cypress/e2e/projects.cy.ts
- client/cypress/utils/e2e.ts
- client/cypress/utils/onboarding.ts
- client/cypress/utils/types.ts
- client/src/components/Allocation/AllocationSummaryProject/AllocationSummaryProject.tsx
- client/src/components/Metrics/MetricsEpoch/MetricsEpochGridFundsUsage/MetricsEpochGridFundsUsage.tsx
- client/src/components/Projects/ProjectsList/ProjectsList.tsx
- client/src/components/shared/ProjectAllocationDetailRow/ProjectAllocationDetailRow.tsx
- client/src/components/ui/PieChart/PieChart.tsx
- client/src/hooks/queries/useProjectsIpfs.ts
- client/src/hooks/queries/useProjectsIpfsWithRewards.ts
- client/src/views/MetricsView/MetricsView.tsx
- localenv/multideployer/server.py
> [SYNC] Master to develop

- backend/app/exceptions.py
- backend/app/infrastructure/__init__.py
> OCT-1864: Add an exception for invalid user address

- client/src/components/Home/HomeRewards/HomeRewards.module.scss
- client/src/components/Home/HomeRewards/HomeRewards.tsx
- client/src/components/shared/ViewTitle/ViewTitle.module.scss
- client/src/components/shared/ViewTitle/ViewTitle.tsx
- client/src/locales/en/translation.json
- client/src/styles/utils/_typography.scss
- client/src/views/HomeView/HomeView.tsx
Check after [PR-388](https://github.com/golemfoundation/octant/pull/388) 
--- …
> OCT-1868: Home: Current rewards + OCT-1869: Home: Total rewards

- client/src/components/Home/HomeGrid/HomeGrid.tsx
- client/src/components/Home/HomeGridPersonalAllocation/HomeGridPersonalAllocation.module.scss
- client/src/components/Home/HomeGridPersonalAllocation/HomeGridPersonalAllocation.tsx
- client/src/components/Home/HomeGridPersonalAllocation/ModalWithdrawEth/ModalWithdrawEth.tsx
- client/src/components/Home/HomeGridPersonalAllocation/ModalWithdrawEth/WithdrawEth/WithdrawEth.module.scss
- client/src/components/Home/HomeGridPersonalAllocation/ModalWithdrawEth/WithdrawEth/WithdrawEth.tsx
- client/src/components/Home/HomeGridPersonalAllocation/ModalWithdrawEth/WithdrawEth/index.tsx
- client/src/components/Home/HomeGridPersonalAllocation/ModalWithdrawEth/WithdrawEth/types.ts
- client/src/components/Home/HomeGridPersonalAllocation/ModalWithdrawEth/index.tsx
- client/src/components/Home/HomeGridPersonalAllocation/ModalWithdrawEth/types.ts
- client/src/components/Home/HomeGridPersonalAllocation/index.tsx
- client/src/components/Home/HomeGridPersonalAllocation/types.ts
- client/src/locales/en/translation.json
Check after [PR-398](https://github.com/golemfoundation/octant/pull/398)
--- …
> OCT-1872: Home: Personal allocation

- client/src/components/Home/HomeGrid/HomeGrid.tsx
- client/src/components/Projects/ProjectsList/ProjectsList.module.scss
- client/src/components/Projects/ProjectsList/ProjectsList.tsx
> OCT-1881 Projects: Grid

- client/src/components/Home/HomeGrid/HomeGrid.tsx
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimator.module.scss
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimator.tsx
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimatorEpochDaysSelector/HomeGridRewardsEstimatorEpochDaysSelector.module.scss
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimatorEpochDaysSelector/HomeGridRewardsEstimatorEpochDaysSelector.tsx
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimatorEpochDaysSelector/index.tsx
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimatorEpochDaysSelector/types.ts
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimatorEstimates/HomeGridRewardsEstimatorEstimates.module.scss
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimatorEstimates/HomeGridRewardsEstimatorEstimates.tsx
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimatorEstimates/index.tsx
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimatorEstimates/types.ts
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimatorUqSelector/HomeGridRewardsEstimatorUqSelector.module.scss
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimatorUqSelector/HomeGridRewardsEstimatorUqSelector.tsx
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimatorUqSelector/index.tsx
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimatorUqSelector/types.ts
- client/src/components/Home/HomeGridRewardsEstimator/index.tsx
- client/src/components/Home/HomeGridRewardsEstimator/types.ts
- client/src/locales/en/translation.json
Check after [PR-400](https://github.com/golemfoundation/octant/pull/400)
--- …
> OCT-1877: Home: Rewards estimator

- backend/tests/api-e2e/test_api_rewards.py
- backend/tests/api-e2e/test_api_snapshot.py
- backend/tests/api-e2e/test_api_withdrawals.py
- backend/tests/conftest.py
> OCT-1598 rewards api sanity test

- client/src/components/Projects/ProjectsList/ProjectsList.module.scss
- client/src/components/Projects/ProjectsList/ProjectsList.tsx
- client/src/locales/en/translation.json
- client/src/views/ProjectsView/ProjectsView.module.scss
- client/src/views/ProjectsView/ProjectsView.tsx
> OCT-1879 Projects: Search - UI (old searcher)

- .github/pull_request_template.md
> OCT-1938: Propose a changelog

- client/src/components/Home/HomeGridTransactions/TransactionsList/TransactionsList.tsx
> OCT-1962: Transactions component shows the same transaction twice

- client/src/views/ProjectsView/ProjectsView.tsx
> OCT-1959 Launching projects view focuses on project search on mobile

- client/src/styles/index.scss
> OCT-1978 Fix buttons using Arial instead of Inter

- client/src/styles/utils/_variables.scss
> OCT-1984 Make toggle switch animation faster

- client/src/components/Metrics/MetricsGrid/MetricsGridTile/MetricsGridTile.module.scss
> OCT-1986 Change metrics tile title font size: 10px => 12px

- client/src/components/shared/Layout/LayoutTopBar/LayoutTopBar.module.scss
> OCT-1989 Adjust mobile top nav calendar so it doesn't break into two lines

- client/src/components/Home/HomeGridEpochResults/EpochResults/EpochResults.module.scss
- client/src/components/Home/HomeGridEpochResults/EpochResults/EpochResults.tsx
- client/src/components/Home/HomeGridEpochResults/EpochResults/types.ts
- client/src/components/Home/HomeGridEpochResults/EpochResultsDetails/EpochResultsDetails.module.scss
- client/src/components/Home/HomeGridEpochResults/EpochResultsDetails/EpochResultsDetails.tsx
- client/src/components/Home/HomeGridEpochResults/EpochResultsDetails/types.ts
- client/src/components/Home/HomeGridEpochResults/HomeGridEpochResults.tsx
- client/src/locales/en/translation.json
> OCT-1972: Add load state to new Home epoch stats chart

- client/src/components/Home/HomeGridDonations/HomeGridDonations.tsx
- client/src/components/ui/Button/Button.module.scss
- client/src/components/ui/Button/types.ts
> OCT-1988 Donations tile edit button: adjust radius

- client/src/components/Home/HomeGridUQScore/HomeGridUQScore.tsx
- client/src/components/ui/Button/Button.module.scss
- client/src/components/ui/Button/Button.tsx
- client/src/components/ui/Button/types.ts
> OCT-1991 Improvements to UQ tile hover states

- client/src/components/ui/InputSelect/InputSelect.tsx
- client/src/components/ui/Svg/Svg.tsx
> OCT-1985 InputSelect: allow closing by clicking chevron

- client/src/components/Allocation/Allocation.tsx
> OCT-1857 Call PUT /antisybil-status in allocate drawer

- client/src/hooks/helpers/useOnboardingSteps/steps.tsx
- client/src/locales/en/translation.json
> OCT-1961 Adjust onboarding copy

- backend/app/infrastructure/routes/projects.py
- backend/app/modules/projects/details/controller.py
- backend/app/modules/projects/details/service/projects_details.py
- backend/tests/modules/projects/details/test_projects_filtering.py
> OCT-1992: Extend searching functionality for multiple params

- client/src/components/Allocation/Allocation.tsx
- client/src/components/Allocation/AllocationNavigation/AllocationNavigation.module.scss
- client/src/components/Allocation/AllocationNavigation/AllocationNavigation.tsx
- client/src/components/Home/HomeGridTransactions/TransactionLabel/TransactionLabel.tsx
- client/src/components/Settings/Settings.tsx
- client/src/locales/en/translation.json
- client/src/services/toastService.ts
> OCT-1899: Improve the allocation confirmation notification

- backend/app/constants.py
- backend/app/modules/user/antisybil/core.py
- backend/tests/conftest.py
- backend/tests/modules/user/antisybil/test_antisybil.py
2. [x] Acceptance criteria are met.
3. [x] PR is manually tested before the merge by developer(s).
5. [x] Unit tests are added unless there is a reason to omit them.
6. [x] Automated tests are added when required.
--- …
> OCT-1923 Assign zero score to GTC staking stamps 

- client/src/components/Home/HomeGridEpochResults/EpochResults/EpochResults.module.scss
- client/src/components/Home/HomeGridEpochResults/EpochResultsBar/EpochResultsBar.module.scss
- client/src/components/Home/HomeGridEpochResults/EpochResultsBar/EpochResultsBar.tsx
- client/src/components/Home/HomeGridEpochResults/HomeGridEpochResults.tsx
> OCT-1976: Fix epoch live results bouncing

- backend/app/modules/uq/service/preliminary.py
- backend/tests/modules/uq/conftest.py
- backend/tests/modules/uq/test_preliminary_uq.py
> OCT-1939: Fix improper way of handling an antisybil_status field

- client/src/components/Home/HomeGridEpochResults/HomeGridEpochResults.tsx
- client/src/components/Project/ProjectListItem/ProjectListItem.module.scss
- client/src/components/Project/ProjectListItem/ProjectListItem.tsx
- client/src/components/Project/ProjectListItemHeader/ProjectListItemHeader.module.scss
- client/src/components/Project/ProjectListItemHeader/ProjectListItemHeader.tsx
- client/src/components/shared/ButtonAddToAllocate/ButtonAddToAllocate.module.scss
- client/src/components/shared/ButtonAddToAllocate/ButtonAddToAllocate.tsx
- client/src/components/shared/ButtonAddToAllocate/ButtonAddToAllocateIcon/ButtonAddToAllocateIcon.module.scss
- client/src/components/shared/ButtonAddToAllocate/ButtonAddToAllocateIcon/ButtonAddToAllocateIcon.tsx
- client/src/components/shared/ButtonAddToAllocate/ButtonAddToAllocateIcon/index.tsx
- client/src/components/shared/ButtonAddToAllocate/ButtonAddToAllocateIcon/types.ts
- client/src/components/shared/ButtonAddToAllocate/types.ts
- client/src/components/shared/Layout/Layout.module.scss
- client/src/components/shared/Layout/Layout.tsx
- client/src/components/shared/Layout/LayoutTopBar/LayoutTopBar.tsx
- client/src/components/shared/RewardsWithoutThreshold/RewardsWithoutThreshold.module.scss
- client/src/components/shared/RewardsWithoutThreshold/RewardsWithoutThreshold.tsx
- client/src/components/shared/RewardsWithoutThreshold/types.ts
- client/src/components/ui/Button/Button.module.scss
- client/src/locales/en/translation.json
- client/src/styles/utils/_typography.scss
- client/src/views/ProjectView/ProjectView.module.scss
- client/src/views/ProjectView/ProjectView.tsx
> OCT-2009: Implement Project Detail view breakpoints

- client/src/components/Home/HomeGrid/HomeGrid.tsx
- client/src/components/Home/HomeGridEpochResults/HomeGridEpochResults.tsx
- client/src/components/shared/Layout/LayoutTopBar/LayoutTopBar.tsx
> OCT-1977: Change the Hierarchy of the Personal Allocation & and Donation modules in the new UI dashboard

- backend/app/exceptions.py
- backend/app/infrastructure/routes/projects.py
- backend/app/infrastructure/routes/validations/project_details_input.py
> OCT-1992: Fix the projects details schema

- client/src/components/Allocation/Allocation.tsx
- client/src/components/ui/Drawer/Drawer.tsx
- client/src/constants/animations.ts
> OCT-2014: Mobil view change to Allocation View is not smooth

- client/src/components/Home/HomeRewards/HomeRewards.module.scss
- client/src/components/Home/HomeRewards/HomeRewards.tsx
- client/src/locales/en/translation.json
> OCT-2021: Implement Rewards Rate tooltip

- client/src/components/shared/Layout/LayoutTopBarCalendar/CalendarItem/CalendarItem.module.scss
- client/src/components/shared/Layout/LayoutTopBarCalendar/CalendarItem/CalendarItem.tsx
- client/src/components/shared/Layout/LayoutTopBarCalendar/CalendarItem/types.ts
- client/src/constants/milestones.ts
- client/src/locales/en/translation.json
> OCT-2020: Calendar tiles should be all caps not title case

- client/src/components/Projects/ProjectsList/ProjectsList.module.scss
- client/src/styles/utils/_mixins.scss
> OCT-2019: Project view tiles padding should be same vertically & horizontally

- client/src/components/Home/HomeGridDonations/HomeGridDonations.module.scss
- client/src/components/Home/HomeGridDonations/HomeGridDonations.tsx
- client/src/locales/en/translation.json
> OCT-2016: Add view projects functionality to Donations module empty state on Home view

- client/src/components/shared/Layout/Layout.module.scss
- client/src/components/shared/Layout/Layout.tsx
- client/src/components/shared/Layout/LayoutFooter/LayoutFooter.module.scss
- client/src/components/shared/Layout/LayoutTopBar/LayoutTopBar.module.scss
- client/src/styles/utils/_mediaQueries.scss
- client/src/styles/utils/_mixins.scss
> OCT-2013: Adjust tile max widths, margins & padding to improve responsiveness

- client/src/components/ui/InputSelect/InputSelect.module.scss
- client/src/components/ui/InputText/InputText.module.scss
> OCT-2022 Projects view: add inputs missing hover states

- client/src/components/shared/Layout/Layout.tsx
> OCT-2027: Mobile navbar has bugs

- client/src/components/Project/ProjectListItemHeader/ProjectListItemHeader.module.scss
- client/src/components/Project/ProjectListItemHeader/ProjectListItemHeader.tsx
> OCT-2032 Project detail view - long URLs should be truncated

- client/src/components/Allocation/Allocation.tsx
- client/src/components/Allocation/AllocationRewardsBox/AllocationRewardsBox.module.scss
- client/src/components/Allocation/AllocationRewardsBox/AllocationRewardsBox.tsx
- client/src/components/Allocation/AllocationRewardsBox/types.ts
- client/src/components/Allocation/AllocationSliderBox/AllocationSliderBox.module.scss
- client/src/components/Allocation/AllocationSliderBox/AllocationSliderBox.tsx
- client/src/components/Allocation/AllocationSliderBox/types.ts
- client/src/locales/en/translation.json
> OCT-2026 Move manual badge in Allocate view

- client/src/components/Metrics/MetricsEpoch/MetricsEpochGridFundsUsage/MetricsEpochGridFundsUsage.module.scss
> OCT-2033 Metrics Epoch funds usage tile layout fixes

- client/src/components/Home/HomeGridEpochResults/EpochResultsBar/EpochResultsBar.module.scss
- client/src/components/Home/HomeGridEpochResults/EpochResultsBar/EpochResultsBar.tsx
> OCT-2030 Improve Avatar cursor for Home chart

- client/src/components/Home/HomeGridPersonalAllocation/HomeGridPersonalAllocation.tsx
> OCT-2043 Personal allocation crypto value should be ETH not GLM

- client/src/components/ui/InputText/InputText.module.scss
> OCT-2049 Search placeholder text & icon should be #9EA39E

- client/src/components/Home/HomeRewards/HomeRewards.tsx
> OCT-2045 Remove tooltips for current & total rewards

- client/src/components/shared/Layout/LayoutFooter/LayoutFooter.module.scss
> OCT-2047: Add desktop footer hover states

- client/src/components/ui/Drawer/Drawer.module.scss
- client/src/components/ui/Drawer/Drawer.tsx
> OCT-2041 Drawers should be closable by clicking outside of them

- client/src/components/ui/InputSelect/InputSelect.module.scss
- client/src/components/ui/InputSelect/InputSelect.tsx
> OCT-2050: Improve layout & usability of Projects → Sort dropdown

- client/src/components/Allocation/Allocation.module.scss
- client/src/components/Home/HomeGridUQScore/HomeGridUQScoreAddresses/HomeGridUQScoreAddresses.module.scss
- client/src/components/Project/ProjectListItemHeader/ProjectListItemHeader.module.scss
- client/src/components/Settings/Settings.module.scss
- client/src/components/shared/ViewTitle/ViewTitle.module.scss
- client/src/components/ui/DoubleValue/DoubleValue.module.scss
- client/src/styles/utils/_mixins.scss
> OCT-1983: Display text (32px +) should all use Inter Tight font not Inter

- client/index.html
> OCT-2011: Analytics: implement in Octant.app

- client/src/components/Home/HomeRewards/HomeRewards.module.scss
- client/src/components/Home/HomeRewards/HomeRewards.tsx
> OCT-2028: Mobile Home view layout issues

- client/src/components/Allocation/AllocationSummary/AllocationSummary.tsx
> [HOTFIX] Allocation leverage outside AW not available

- backend/migrations/ipfs_integration/config.py
- backend/migrations/ipfs_integration/files/cids.md
- backend/migrations/ipfs_integration/files/ipfs_projects_details_epoch_5.json
- backend/migrations/versions/2060b4c232c6_add_projects_details_from_ipfs_for_.py
> OCT-2079: Add projects for E5

- client/src/components/shared/Layout/LayoutTopBar/LayoutTopBar.tsx
- client/src/views/ProjectView/ProjectView.tsx
> OCT-2087: Fix scroll position when entering project view

- backend/migrations/versions/5398b1538a31_remove_existing_delegations_before_e5_s_.py
> OCT-2091: Truncate existing delegation-related data should be removed

- client/src/components/shared/Layout/LayoutTopBarCalendar/LayoutTopBarCalendar.module.scss
> HOTFIX: calendar desktop position

- client/src/components/Allocation/Allocation.module.scss
- client/src/components/Allocation/Allocation.tsx
- client/src/components/Allocation/AllocationSummary/AllocationSummary.module.scss
- client/src/hooks/helpers/useAllocationViewSetRewardsForProjects.ts
- client/src/locales/en/translation.json
> [HOTFIX]: Allocation summary empty state + match funding

- client/src/components/Home/HomeGridUQScore/ModalRecalculatingScore/RecalculatingScore/RecalculatingScore.tsx
- client/src/constants/delegation.ts
- client/src/constants/localStorageKeys.ts
> [HOTFIX]: delegation epoch 5

- backend/app/modules/score_delegation/core.py
- backend/app/modules/user/antisybil/core.py
- backend/tests/modules/score_delegation/test_score_delegation_core.py
- backend/tests/modules/user/antisybil/test_antisybil.py
> [HOTFIX] Timeout List inconsistency: lowercase the addresses

- client/src/components/ui/DoubleValue/DoubleValue.module.scss
> [HOTFIX]: double value secondary tiny, small

- client/src/components/Home/HomeGridEpochResults/HomeGridEpochResults.tsx
> [HOTFIX]: home epoch results - estimated rewards when AW is open

- client/src/components/Home/HomeGridEpochResults/HomeGridEpochResults.tsx
- client/src/components/ui/DoubleValue/DoubleValue.module.scss
> [SYNC] Master => develop 

- client/src/api/calls/vimeo.ts
> [HOTFIX]: videos manual sort

- client/src/components/Allocation/Allocation.module.scss
- client/src/components/Home/HomeGridCurrentGlmLock/HomeGridCurrentGlmLock.module.scss
- client/src/components/Home/HomeGridCurrentGlmLock/HomeGridCurrentGlmLock.tsx
- client/src/components/Home/HomeGridPersonalAllocation/HomeGridPersonalAllocation.module.scss
- client/src/components/Home/HomeGridPersonalAllocation/HomeGridPersonalAllocation.tsx
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimator.module.scss
- client/src/components/Home/HomeGridRewardsEstimator/HomeGridRewardsEstimator.tsx
- client/src/components/Home/HomeGridUQScore/HomeGridUQScore.module.scss
- client/src/components/ui/DoubleValue/DoubleValue.module.scss
> OCT-2051: Improve Home view tile layouts on mobile & OCT-2102: Polish layout of Rewards estimator & UQ Tiles

- client/src/components/Home/HomeGridCurrentGlmLock/HomeGridCurrentGlmLock.tsx
- client/src/components/Home/HomeGridPersonalAllocation/HomeGridPersonalAllocation.tsx
- client/src/locales/en/translation.json
…le fix (admin mode)
---
(1) Developer(s) in coordination with QA decide whether it's required. For small tickets introducing small …
> OCT-2057: Improve Effective Balance tooltip

- client/src/utils/regExp.test.ts
- client/src/utils/regExp.ts
> OCT-2115 Project page Search function showing multiples

- client/src/components/shared/Layout/LayoutNavbar/LayoutNavbar.module.scss
- client/src/components/shared/Layout/LayoutNavbar/LayoutNavbar.tsx
- client/src/hooks/helpers/useNavigationTabs.tsx
- client/src/svg/navigation.ts
- client/src/types/navigationTabs.ts
> OCT-2078: Fix menu bar icon sizes in desktop views

- client/src/constants/milestones.ts
> OCT-2082: Epoch timeline: events for E6: client

- client/src/components/shared/Layout/LayoutFooter/LayoutFooter.module.scss
- client/src/components/shared/Layout/LayoutFooter/LayoutFooter.tsx
- client/src/locales/en/translation.json
> OCT-2071: Implement email subscription field for Octant app

- epoch-verifier/src/data/models.ts
- epoch-verifier/src/verifications/donations.ts
> Fix: Fix totalWithdrawals in the epoch verifier

- client/package.json
- client/src/api/clients/client-wagmi.ts
- client/yarn.lock
> OCT-2173 Add injected connector

- client/src/locales/en/translation.json
> [HOTFIX] Typo in onboarding

- client/src/api/calls/vimeo.ts
- client/src/components/Home/HomeGridVideoBar/HomeGridVideoBar.module.scss
- client/src/components/Home/HomeGridVideoBar/HomeGridVideoBar.tsx
- client/src/components/Home/HomeGridVideoBar/VideoTile/VideoTile.module.scss
- client/src/components/Home/HomeGridVideoBar/VideoTile/VideoTile.tsx
- client/src/components/Home/HomeGridVideoBar/VideoTile/types.ts
- client/src/components/Metrics/MetricsEpoch/MetricsEpochHeader/MetricsEpochHeader.module.scss
- client/src/components/Metrics/MetricsEpoch/MetricsEpochHeader/MetricsEpochHeader.tsx
- client/src/components/shared/Layout/LayoutFooter/LayoutFooter.tsx
- client/src/components/shared/NavigationArrows/NavigationArrows.module.scss
- client/src/components/shared/NavigationArrows/NavigationArrows.tsx
- client/src/components/shared/NavigationArrows/index.tsx
- client/src/components/shared/NavigationArrows/types.ts
- client/src/hooks/helpers/useMediaQuery/index.ts
- client/src/locales/en/translation.json
- client/src/styles/utils/_mixins.scss
> OCT-2157: Improve Learn video bar display & OCT-2187: Small fix for video bar on mobile

- raffle-weights/calc_weights.py
Calculates the raffle weights for given addresses using total allocations in epoch
---
(1) Developer(s) in coordination with QA decide …
> OCT-2179: Script to calculate raffle weights

- client/src/components/Project/ProjectMilestones/ProjectMilestones.module.scss
> OCT-2171 Change Reporting content column background colour to bring inline with design

- client/src/components/shared/Layout/LayoutTopBar/LayoutTopBar.module.scss
> OCT-2176 Make the added projects badge red

- backend/tests/conftest.py
> OCT-2194: API Tests failures fixes

- client/src/components/Home/HomeGridTransactions/HomeGridTransactions.module.scss
- client/src/components/Home/HomeGridTransactions/HomeGridTransactions.tsx
> OCT-2169 Historical transactions are not loading for the user once scrolled down

- client/src/locales/en/translation.json
> OCT-2180 Typo in projects ordering option

- backend/app/infrastructure/graphql/epochs.py
- backend/app/infrastructure/graphql/withdrawals.py
> OCT-1746: Add caching for GQL methods

- client/src/constants/milestones.ts
> [HOTFIX] Missing milestones allocation alert state

- client/cypress/e2e/_10calendar_openAW.cy.ts
- client/src/components/shared/Layout/LayoutTopBarCalendar/CalendarItem/CalendarItem.tsx
> OCT-2255 The in-app clock should adjust to the user’s time zone

- client/cypress/e2e/_15closeAW.cy.ts
- client/cypress/e2e/_16allocationAWClosed.cy.ts
- client/src/components/Allocation/Allocation.tsx
- client/src/components/Allocation/AllocationItem/AllocationItem.tsx
- client/src/components/Allocation/AllocationNavigation/AllocationNavigation.tsx
- client/src/components/Allocation/AllocationRewardsBox/AllocationRewardsBox.tsx
> OCT-2124: Allocation AW Closed E2E

- client/index.html
- client/public/fail.html
> [HOTFIX]: favicon

- backend/app/modules/user/events_generator/core.py
- backend/tests/modules/user/events_generator/test_unify_deposit_balances.py
> OCT-2269: Fix bug for moving deposit from Sablier between epochs

- client/cypress/e2e/_17project.cy.ts
> [FIX] E2E CY project suit flaky

- ci/argocd/templates/octant-application.yaml
> caqd-369: update backend postgresql max_connections

- client/cypress/e2e/_20languageSelection.cy.ts
> [HOTFIX] E2E Language selection: InputSelect scrollIntoView

- backend/app/modules/facades/confirm_multisig.py
Processing of all pending multisigs fails when any is corrupted failing the whole batch. We want to avoid that and process all that are ok, and log the ones failing
> Oct-2336: Processing of all pending multisigs fails when any is corrupted 

- client/src/components/Home/HomeGridPersonalAllocation/ModalWithdrawEth/WithdrawEth/WithdrawEth.tsx
> OCT-2326 Estimated gas price during withdrawal is zero

- client/cypress/e2e/group2/_09settings.cy.ts
- client/src/components/shared/Layout/LayoutFooter/LayoutFooter.module.scss
- client/src/components/ui/InputSelect/InputSelect.module.scss
- client/src/components/ui/InputSelect/InputSelect.tsx
> OCT-2141 Filtering list of projects - arrow icon is not clickable

- client/cypress/e2e/group1/_07layoutFooter.cy.ts
- client/src/constants/urls.ts
> OSU-414 Migrate Brand Kit Link in Footer to New Figma Document

- client/src/constants/milestones.ts
> OCT-2347 Epoch timeline: events for E7: client

- backend/migrations/versions/c737027a131a_remove_pending_signatures_before_e7.py
> OCT-2350: Remove all pending signatures before 2025 Feb 4

- .github/workflows/tpl-deploy-app.yml
- backend/app/constants.py
- backend/tests/modules/projects/metadata/test_projects_retrieval.py
- backend/v2/core/dependencies.py
- backend/v2/projects/dependencies.py
> OCT-2357: Fix issue with IPFS for E6

- client/cypress/e2e/group1/_07layoutFooter.cy.ts
- client/cypress/e2e/group2/_03homeGLMLock.cy.ts
- client/src/components/Home/HomeGridTransactions/ModalTransactionDetails/ModalTransactionDetails.tsx
> [FIX]: homeGlmLock invoke text

- backend/tests/v2/users/conftest.py
- backend/tests/v2/users/test_get_patrons_for_epoch.py
- backend/v2/main.py
- backend/v2/user_patron_mode/repositories.py
- backend/v2/users/router.py
- backend/v2/users/schemas.py
migrate: `/user/patrons/{epoch}`
> OCT-2290: migrate: `/user/patrons/{epoch_number}`

- backend/tests/conftest.py
> OCT-2066: Additional logs to flaky API tests for intestigation

- client/src/constants/milestones.ts
> OCT-2358 Fix the project submission closing date in the app's calendar

- backend/tests/v2/users/test_tos.py
- backend/v2/sablier/subgraphs.py
- backend/v2/users/dependencies.py
- backend/v2/users/repositories.py
- backend/v2/users/router.py
- backend/v2/users/schemas.py
Migrate:
- `GET /user/{user_address>/sablier-streams `
- `GET /user/sablier-streams/all`
> OCT-2368: migrate `sablier-streams`

- backend/tests/api-e2e/conftest.py
> OCT-2362: Mocks sablier for api tests

- backend/tests/conftest.py
- backend/tests/helpers/custom_flask_client.py
> OCT-2324: Add logging on flask_client level

- backend/v2/allocations/socket.py
Fixing allocation via ws.
---
(1) Developer(s) in coordination with QA decide whether it's required. For small tickets introducing …
> [FIX] Allocation websocket not working

- backend/migrations/versions/7d5968807420_e7_truncate_existing_delegations_and_gp_.py
Adds e7 truncation of delegations and gp stamps
---
(1) Developer(s) in coordination with QA decide whether it's required. For small …
> OCT-2400: Adds e7 truncation of delegations and gp stamps

- client/src/locales/en/translation.json
- client/src/locales/es/translation.json
> [HOTFIX] Gitcoin Passport rename to Passport XYZ

- backend/migrations/versions/2a2ced0a6aa7_e7_remove_stuck_multisig_allocation_.py
Removes stuck and duplicated multisig allocation request for user `0x25854e2a49A6CDAeC7f0505b4179834509038549`
> OCT-2404: Removes stuck and duplicated multisig allocation request for given user

- backend/tests/api_e2e/README.md
- localenv/multideployer/server.py
> [DOCS] Document API tests

- client/src/api/calls/delegate.ts
While building url for delegations we should have it as `{url}/delegations..` but actually create it with double `//` so it's trying to access non-existent path `{url}//delegations...`
8. [ ] Tech documentation is added / updated, reviewed and approved (including mandatory approval by a code owner, should such …
> [HOTFIX] Remove / from delegate API call

- client/src/components/Allocation/AllocationSummaryProject/AllocationSummaryProject.tsx
Resolves issue with wrong CID when user has made allocations in prev epoch and CID for next epoch is available. 
---
(1) Developer(s) …
> [HOTFIX]: AllocationSummary
